### ISSUE TITLE
Edge Browser is not working.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-selenium#48]
Following error logs are generated when user tries to run tests in Edge Browser:

```
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: MicrosoftWebDriver.exe should be installed in an elevated command prompt executing: dism /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:715)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:540)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at com.github.wasiqb.coteafs.selenium.core.Browser.setupEdgeDriver(Browser.java:169)
	at com.github.wasiqb.coteafs.selenium.core.Browser.setupDriver(Browser.java:153)
	at com.github.wasiqb.coteafs.selenium.core.Browser.start(Browser.java:225)
	at com.github.wasiqb.coteafs.selenium.core.BrowserTest.setupTest(BrowserTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:529)
	at org.testng.TestRunner.run(TestRunner.java:497)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: MicrosoftWebDriver.exe should be installed in an elevated command prompt executing: dism /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0
	at io.github.bonigarcia.wdm.WebDriverManager.checkInsiderVersion(WebDriverManager.java:599)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:499)
	... 29 more

```

**Comment by WasiqB** [comment]
This is not our issue nor it's `WebDriverManager` issue.

You need to do the following once:

- Open `CMD` in Administrative mode.
- Run `DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0`

That's it.
